# Movie Analytics Pipeline

A Python data project that transforms raw iPhone Notes movie logs into structured datasets and performs behavioral analysis using Pandas.

## 1. Data Ingestion
Loading raw movie logs from iPhone Notes text file.

In [2]:
import pandas as pd
import re
with open("data/movies_raw.txt", "r") as f:
    lines = f.readlines()

## 2. Data Parsing

Using regex and string extraction to convert raw text logs into structured movie records.

In [4]:
data = []

for line in lines:
    line = line.strip()

    if line == "":
        continue

    parts = line.split(" - ", 1)

    if len(parts) != 2:
        continue

    date = parts[0]
    rest = parts[1]

    matches = re.findall(r"\((\d+)\)", rest)

    if len(matches) < 2:
        continue

    rating = int(matches[0])
    watch_number = int(matches[1])

    title = re.sub(r"\(\d+\)\s*\(\d+\)", "", rest).strip()

    data.append([date, title, rating, watch_number])

In [5]:
df = pd.DataFrame(data, columns=["date", "title", "rating", "watch_number"])
df.head()

      date               title  rating  watch_number
0   1-3-25  It’s what’s inside       6             1
1   1-8-25         phantasm II       6             2
2   1-8-25         rear window       7             3
3  1-10-25        phantasm III       2             4
4  1-11-25       self reliance       5             5

In [7]:
df["year"] = df["date"].dt.year

In [8]:
df.groupby("year")["title"].count()

year
2025    101
2026     28
Name: title, dtype: int64

In [9]:
df.groupby("year")["rating"].mean()

year
2025    5.495050
2026    5.785714
Name: rating, dtype: float64

In [10]:
df.sort_values("rating", ascending=False).head(10)

          date                           title  rating  watch_number  year
17  2025-02-26              Dallas buyers club       9            18  2025
99  2025-12-31                   Marty supreme       9            99  2025
33  2025-05-29                  bring her back       9            34  2025
123 2026-04-20                    ready or not       8            23  2026
27  2025-04-11                         warfare       8            28  2025
42  2025-07-13  one flew over the cuckoos nest       8            43  2025
51  2025-08-15                       Chinatown       8            51  2025
32  2025-05-15  the good, the bad and the ugly       8            33  2025
8   2025-01-30                       companion       8             9  2025
87  2025-12-09              memories of murder       8            87  2025

In [11]:
df["date"] = pd.to_datetime(df["date"])
df["year"] = df["date"].dt.year

In [12]:
df.head(10)

        date                title  rating  watch_number  year
0 2025-01-03   It’s what’s inside       6             1  2025
1 2025-01-08          phantasm II       6             2  2025
2 2025-01-08          rear window       7             3  2025
3 2025-01-10         phantasm III       2             4  2025
4 2025-01-11        self reliance       5             5  2025
5 2025-01-20           maniac cop       4             6  2025
6 2025-01-26             presence       7             7  2025
7 2025-01-28        the substance       7             8  2025
8 2025-01-30            companion       8             9  2025
9 2025-02-02  my bloody valentine       6            10  2025

In [13]:
df.info()

<class 'pandas.DataFrame'>
Index: 129 entries, 0 to 128
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          129 non-null    datetime64[us]
 1   title         129 non-null    str
 2   rating        129 non-null    int64
 3   watch_number  129 non-null    int64
 4   year          129 non-null    int32
dtypes: datetime64[us](1), int32(1), int64(2), str(1)
memory usage: 5.5 KB

In [14]:
df.describe()

                             date      rating  watch_number         year
count                         129  129.000000    129.000000   129.000000
mean   2025-09-15 09:51:37.674418    5.558140     42.643411  2025.217054
min           2025-01-03 00:00:00    2.000000      1.000000  2025.000000
25%           2025-05-15 00:00:00    4.000000     17.000000  2025.000000
50%           2025-10-07 00:00:00    6.000000     37.000000  2025.000000
75%           2025-12-29 00:00:00    7.000000     68.000000  2025.000000
max           2026-05-03 00:00:00    9.000000    100.000000  2026.000000
std                           NaN    1.699756     29.778820     0.413847

In [15]:
lines[:5]

['1-3-25 - It’s what’s inside (6) (1)\n',
 '1-8-25 - phantasm II (6) (2)\n',
 '1-8-25 - rear window (7) (3)\n',
 '1-10-25 - phantasm III (2) (4)\n',
 '1-11-25 - self reliance (5) (5)\n']

In [16]:
with open("data/movies_raw.txt", "r") as f:
    print(f.read()[:500])

1-3-25 - It’s what’s inside (6) (1)
1-8-25 - phantasm II (6) (2)
1-8-25 - rear window (7) (3)
1-10-25 - phantasm III (2) (4)
1-11-25 - self reliance (5) (5)
1-20-25 - maniac cop (4) (6)
1-26-25 - presence (7) (7)
1-28-25 - the substance (7) (8)
1-30-25 - companion (8) (9)
2-2-25 - my bloody valentine (6) (10)
2-10-25 - heart eyes (4) (11)
2-11-25 - woman of the hour (7) (12)
2-11-25 - final destination (5) (13)
2-12-25 - child’s play (7) (14)
2-19-25 - killer klowns from outer space (4) (15)
2-2

In [17]:
with open("data/movies_raw.txt", "r") as f:
    lines = f.readlines()

In [18]:
import re

data = []

for line in lines:
    line = line.strip()

    if line == "":
        continue

    parts = line.split(" - ", 1)

    if len(parts) != 2:
        continue

    date = parts[0]
    rest = parts[1]

    matches = re.findall(r"\((\d+)\)", rest)

    if len(matches) < 2:
        continue

    rating = int(matches[0])
    watch_number = int(matches[1])

    title = re.sub(r"\(\d+\)\s*\(\d+\)", "", rest).strip()

    data.append([date, title, rating, watch_number])

In [19]:
df = pd.DataFrame(
    data,
    columns=["date", "title", "rating", "watch_number"]
)

df["date"] = pd.to_datetime(df["date"], format="%m-%d-%y")

df["year"] = df["date"].dt.year

df.head()

        date               title  rating  watch_number  year
0 2025-01-03  It’s what’s inside       6             1  2025
1 2025-01-08         phantasm II       6             2  2025
2 2025-01-08         rear window       7             3  2025
3 2025-01-10        phantasm III       2             4  2025
4 2025-01-11       self reliance       5             5  2025

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 129 entries, 0 to 128
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          129 non-null    datetime64[us]
 1   title         129 non-null    str
 2   rating        129 non-null    int64
 3   watch_number  129 non-null    int64
 4   year          129 non-null    int32
dtypes: datetime64[us](1), int32(1), int64(2), str(1)
memory usage: 4.7 KB

In [21]:
df.groupby("year")["title"].count()

year
2025    101
2026     28
Name: title, dtype: int64

In [22]:
df.groupby("year")["title"].count()

year
2025    101
2026     28
Name: title, dtype: int64

In [23]:
df.groupby("year")["rating"].mean()

year
2025    5.495050
2026    5.785714
Name: rating, dtype: float64

In [24]:
df.sort_values("rating", ascending=False).head(10)

          date                           title  rating  watch_number  year
17  2025-02-26              Dallas buyers club       9            18  2025
99  2025-12-31                   Marty supreme       9            99  2025
33  2025-05-29                  bring her back       9            34  2025
123 2026-04-20                    ready or not       8            23  2026
27  2025-04-11                         warfare       8            28  2025
42  2025-07-13  one flew over the cuckoos nest       8            43  2025
51  2025-08-15                       Chinatown       8            51  2025
32  2025-05-15  the good, the bad and the ugly       8            33  2025
8   2025-01-30                       companion       8             9  2025
87  2025-12-09              memories of murder       8            87  2025

In [25]:
df.groupby(df["date"].dt.to_period("M"))["title"].count()

date
2025-01     9
2025-02     9
2025-03     6
2025-04     5
2025-05     5
2025-06     8
2025-07     4
2025-08    10
2025-09     6
2025-10     8
2025-11    13
2025-12    18
2026-01     4
2026-02     5
2026-03     7
2026-04    10
2026-05     2
Freq: M, Name: title, dtype: int64

In [26]:
with open("data/movies_raw.txt", "r") as f:
    lines = f.readlines()

In [27]:
df = pd.DataFrame(
    data,
    columns=["date", "title", "rating", "watch_number"]
)

df["date"] = pd.to_datetime(df["date"], format="%m-%d-%y")
df["year"] = df["date"].dt.year

In [28]:
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 129 entries, 0 to 128
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          129 non-null    datetime64[us]
 1   title         129 non-null    str
 2   rating        129 non-null    int64
 3   watch_number  129 non-null    int64
 4   year          129 non-null    int32
dtypes: datetime64[us](1), int32(1), int64(2), str(1)
memory usage: 4.7 KB

        date               title  rating  watch_number  year
0 2025-01-03  It’s what’s inside       6             1  2025
1 2025-01-08         phantasm II       6             2  2025
2 2025-01-08         rear window       7             3  2025
3 2025-01-10        phantasm III       2             4  2025
4 2025-01-11       self reliance       5             5  2025

In [29]:
df.groupby("year")["title"].count()

year
2025    101
2026     28
Name: title, dtype: int64

In [30]:
df.groupby("year")["rating"].mean()

year
2025    5.495050
2026    5.785714
Name: rating, dtype: float64

In [31]:
df.groupby(df["date"].dt.to_period("M"))["title"].count()

date
2025-01     9
2025-02     9
2025-03     6
2025-04     5
2025-05     5
2025-06     8
2025-07     4
2025-08    10
2025-09     6
2025-10     8
2025-11    13
2025-12    18
2026-01     4
2026-02     5
2026-03     7
2026-04    10
2026-05     2
Freq: M, Name: title, dtype: int64

In [32]:
df = df.sort_values("date")
df["rolling_avg_rating"] = df["rating"].rolling(5).mean()

In [33]:
df["rating"].value_counts().sort_index()

rating
2     5
3    11
4    23
5    20
6    26
7    29
8    12
9     3
Name: count, dtype: int64

In [34]:
df.sort_values("rating", ascending=False).head(10)

,date,title,rating,watch_number,year,rolling_avg_rating
17,2025-02-26,Dallas buyers club,9,18,2025,6.0
99,2025-12-31,Marty supreme,9,99,2025,6.6
33,2025-05-29,bring her back,9,34,2025,6.6
123,2026-04-20,ready or not,8,23,2026,7.0
27,2025-04-11,warfare,8,28,2025,5.2
42,2025-07-13,one flew over the cuckoos nest,8,43,2025,6.8
51,2025-08-15,Chinatown,8,51,2025,5.4
32,2025-05-15,"the good, the bad and the ugly",8,33,2025,6.2
8,2025-01-30,companion,8,9,2025,6.2
87,2025-12-09,memories of murder,8,87,2025,5.0

In [35]:
df.sort_values("rating").head(10)

,date,title,rating,watch_number,year,rolling_avg_rating
3,2025-01-10,phantasm III,2,4,2025,NaN
36,2025-06-07,flight risk,2,37,2025,6.4
93,2025-12-21,Christmas evil,2,93,2025,5.4
78,2025-11-22,pilgrim,2,78,2025,5.0
106,2026-02-13,HIM,2,6,2026,4.4
47,2025-08-03,happy Gilmore 2,3,47,2025,5.0
25,2025-04-07,kraven the hunter,3,26,2025,4.6
16,2025-02-24,leprechaun,3,17,2025,5.2
66,2025-10-14,creepshow,3,66,2025,5.0
100,2025-12-31,the Poughkeepsie tapes,3,100,2025,6.0